* -----------------------------------------------------
* XLS2GMS 2.8      45.7.0 64fbf3ce Jan 18, 2024          WEI x86 64bit/MS Window
* Erwin Kalvelagen, GAMS Development Corp.
* -----------------------------------------------------
* Application: Microsoft Excel
* Version:     16.0
* Workbook:    D:\Research\GAMS\Speed of response conference\La Palma\Unified\Input_Lapalma.xlsx
* Sheet:       generators_c
* Range:       $AT$2:$AU$14
* -----------------------------------------------------
     column1
i1   0      
i2   0      
i3   0      
i4   0      
i5   0      
i6   0      
i7   0      
i8   0      
i9   0      
i10  0      
i11  0      
            
* -----------------------------------------------------
