* -----------------------------------------------------
* XLS2GMS 2.8      45.7.0 64fbf3ce Jan 18, 2024          WEI x86 64bit/MS Window
* Erwin Kalvelagen, GAMS Development Corp.
* -----------------------------------------------------
* Application: Microsoft Excel
* Version:     16.0
* Workbook:    D:\Research\GAMS\Speed of response conference\La Palma\Unified\Input_Lapalma.xlsx
* Sheet:       generators_c
* Range:       $D$2:$E$14
* -----------------------------------------------------
     column1
i1   24     
i2   24     
i3   24     
i4   24     
i5   24     
i6   24     
i7   24     
i8   24     
i9   24     
i10  24     
i11  24     
            
* -----------------------------------------------------
