* -----------------------------------------------------
* XLS2GMS 2.8      45.7.0 64fbf3ce Jan 18, 2024          WEI x86 64bit/MS Window
* Erwin Kalvelagen, GAMS Development Corp.
* -----------------------------------------------------
* Application: Microsoft Excel
* Version:     16.0
* Workbook:    D:\Research\GAMS\Speed of response conference\La Palma\Unified\Input_Lapalma.xlsx
* Sheet:       generators_c
* Range:       $V$2:$Z$14
* -----------------------------------------------------
     tr1  tr2  tr3  tr4 
i1   3.82 3.82 3.82 3.82
i2   3.82 3.82 3.82 3.82
i3   3.82 3.82 3.82 3.82
i4   4.3  4.3  4.3  4.3 
i5   6.7  6.7  6.7  6.7 
i6   6.7  6.7  6.7  6.7 
i7   11.2 11.2 11.2 11.2
i8   11.5 11.5 11.5 11.5
i9   11.5 11.5 11.5 11.5
i10  11.5 11.5 11.5 11.5
i11  21   21   21   21  
                        
* -----------------------------------------------------
