* -----------------------------------------------------
* XLS2GMS 2.8      45.7.0 64fbf3ce Jan 18, 2024          WEI x86 64bit/MS Window
* Erwin Kalvelagen, GAMS Development Corp.
* -----------------------------------------------------
* Application: Microsoft Excel
* Version:     16.0
* Workbook:    D:\Research\GAMS\Speed of response conference\La Palma\Unified\Input_Lapalma.xlsx
* Sheet:       generators_c
* Range:       $AB$2:$AF$14
* -----------------------------------------------------
     tr1  tr2  tr3  tr4 
i1   1    1    1    1   
i2   1    1    1    1   
i3   1    1    1    1   
i4   1    1    1    1   
i5   1    1    1    1   
i6   1    1    1    1   
i7   1    1    1    1   
i8   1    1    1    1   
i9   1    1    1    1   
i10  1    1    1    1   
i11  1    1    1    1   
                        
* -----------------------------------------------------
