* -----------------------------------------------------
* XLS2GMS 2.8      45.7.0 64fbf3ce Jan 18, 2024          WEI x86 64bit/MS Window
* Erwin Kalvelagen, GAMS Development Corp.
* -----------------------------------------------------
* Application: Microsoft Excel
* Version:     16.0
* Workbook:    D:\Research\GAMS\Speed of response conference\La Palma\Unified\Input_Lapalma.xlsx
* Sheet:       Dynamics
* Range:       $A$2:$B$14
* -----------------------------------------------------
     column1
i1   1.749  
i2   1.749  
i3   1.749  
i4   1.734  
i5   2.161  
i6   1.878  
i7   2.1    
i8   2.1    
i9   2.1    
i10  2.1    
i11  6.5    
            
* -----------------------------------------------------
