* -----------------------------------------------------
* XLS2GMS 2.8      45.7.0 64fbf3ce Jan 18, 2024          WEI x86 64bit/MS Window
* Erwin Kalvelagen, GAMS Development Corp.
* -----------------------------------------------------
* Application: Microsoft Excel
* Version:     16.0
* Workbook:    D:\Research\GAMS\Conference-IREP\La Palma\Unified\Input_Lapalma.xlsx
* Sheet:       generators_c
* Range:       $AN$2:$AR$14
* -----------------------------------------------------
     tr1  tr2  tr3  tr4 
i1   2.35 2.35 2.35 2.35
i2   2.35 2.35 2.35 2.35
i3   2.35 2.35 2.35 2.35
i4   2.82 2.82 2.82 2.82
i5   3.3  3.3  3.3  3.3 
i6   3.3  3.3  3.3  3.3 
i7   6.63 6.63 6.63 6.63
i8   6.63 6.63 6.63 6.63
i9   6.63 6.63 6.63 6.63
i10  6.63 6.63 6.63 6.63
i11  13   13   13   13  
                        
* -----------------------------------------------------
