* -----------------------------------------------------
* XLS2GMS 2.8      45.7.0 64fbf3ce Jan 18, 2024          WEI x86 64bit/MS Window
* Erwin Kalvelagen, GAMS Development Corp.
* -----------------------------------------------------
* Application: Microsoft Excel
* Version:     16.0
* Workbook:    D:\Research\GAMS\Speed of response conference\La Palma\Unified\Input_Lapalma.xlsx
* Sheet:       Dynamics
* Range:       $G$2:$H$14
* -----------------------------------------------------
     column1         
i1   20              
i2   20              
i3   20              
i4   20              
i5   20              
i6   20              
i7   20              
i8   20              
i9   20              
i10  20              
i11  21.2527964205817
                     
* -----------------------------------------------------
