* -----------------------------------------------------
* XLS2GMS 2.8      45.7.0 64fbf3ce Jan 18, 2024          WEI x86 64bit/MS Window
* Erwin Kalvelagen, GAMS Development Corp.
* -----------------------------------------------------
* Application: Microsoft Excel
* Version:     16.0
* Workbook:    D:\Research\GAMS\Speed of response conference\La Palma\Unified\Input_Lapalma.xlsx
* Sheet:       Dynamics
* Range:       $D$2:$E$14
* -----------------------------------------------------
     column1
i1   5.4    
i2   5.4    
i3   5.4    
i4   6.3    
i5   9.4    
i6   9.6    
i7   15.75  
i8   14.5   
i9   14.5   
i10  14.5   
i11  26.82  
            
* -----------------------------------------------------
