* -----------------------------------------------------
* XLS2GMS 2.8      45.7.0 64fbf3ce Jan 18, 2024          WEI x86 64bit/MS Window
* Erwin Kalvelagen, GAMS Development Corp.
* -----------------------------------------------------
* Application: Microsoft Excel
* Version:     16.0
* Workbook:    D:\Research\GAMS\Speed of response conference\La Palma\Unified\Input_Lapalma.xlsx
* Sheet:       generators_c
* Range:       $BR$2:$BZ$14
* -----------------------------------------------------
     j1   j2   j3   j4   j5   j6   j7   j8  
i1   1    2    3    4    5    6    7    8   
i2   1    2    3    4    5    6    7    8   
i3   1    2    3    4    5    6    7    8   
i4   1    2    3    4    5    6    7    8   
i5   1    2    3    4    5    6    7    8   
i6   1    2    3    4    5    6    7    8   
i7   1    2    3    4    5    6    7    8   
i8   1    2    3    4    5    6    7    8   
i9   1    2    3    4    5    6    7    8   
i10  1    2    3    4    5    6    7    8   
i11  1    2    3    4    5    6    7    8   
                                            
* -----------------------------------------------------
